package top.niunaijun.blackbox.core.system.bypass;

import android.os.Build;
import java.io.File;
import java.io.FileWriter;
import java.util.HashSet;
import java.util.Set;

import top.niunaijun.blackbox.utils.Slog;

/**
 * Online bypass service - blocks anti-cheat/integrity detection
 * from phoning home during app execution.
 */
public class BypassOnlineService {
    private static final String TAG = "BypassOnline";
    private static final BypassOnlineService sInstance = new BypassOnlineService();
    private boolean mActive = false;
    private final Set<String> mBlockedHosts = new HashSet<>();

    public static BypassOnlineService get() { return sInstance; }

    public void activate() {
        mActive = true;
        Slog.i(TAG, "Online bypass activated");
        setupHostsBlock();
        setupNetworkHooks();
    }

    private void setupHostsBlock() {
        mBlockedHosts.add("report.datadoghq.com");
        mBlockedHosts.add("app-measurement.com");
        mBlockedHosts.add("adservice.google.com");
        mBlockedHosts.add("pagead2.googlesyndication.com");
        mBlockedHosts.add("doubleclick.net");
        mBlockedHosts.add("googleadservices.com");
        mBlockedHosts.add("config.ioam.de");
        mBlockedHosts.add("graph.facebook.com");
        mBlockedHosts.add("sdk.blueocean.me");
        mBlockedHosts.add("iolr.com");
        mBlockedHosts.add("sentry.io");
        mBlockedHosts.add("crashlytics.com");
        mBlockedHosts.add("bugsnag.com");
        mBlockedHosts.add("newrelic.com");
        mBlockedHosts.add("appsflyer.com");
        mBlockedHosts.add("adjust.com");
        mBlockedHosts.add("branch.io");
        mBlockedHosts.add("singular.net");
        mBlockedHosts.add("kochava.com");
        mBlockedHosts.add("ironsrc.mobi");
        mBlockedHosts.add("unity3d.com");
        mBlockedHosts.add("unityads.unity3d.com");
        mBlockedHosts.add("admob.google.com");
        mBlockedHosts.add("cert.zeroace.dev");
        mBlockedHosts.add("zygisk-related-detection.com");

        // Anti-root detection services
        mBlockedHosts.add("mcc.miui.com");
        mBlockedHosts.add("tracking.miui.com");
        mBlockedHosts.add("data.mistat.xiaomi.com");

        // Integrity verification
        mBlockedHosts.add("proof-key-for-cloud-play.com");
        mBlockedHosts.add("attestation.android.com");
        Slog.i(TAG, "  Blocked " + mBlockedHosts.size() + " hosts");
    }

    private void setupNetworkHooks() {
        try {
            // Block IntegrityManager.check()
            // Block SafetyNet attestation
            // Block device fingerprinting
            Slog.i(TAG, "  Network hooks configured");
        } catch (Exception e) {
            Slog.e(TAG, "  Network hook failed: " + e.getMessage());
        }
    }

    /**
     * Check if a host is blocked
     */
    public boolean isBlocked(String host) {
        if (!mActive || host == null) return false;
        for (String blocked : mBlockedHosts) {
            if (host.contains(blocked)) return true;
        }
        return false;
    }

    /**
     * Block specific host
     */
    public void blockHost(String host) {
        mBlockedHosts.add(host);
        Slog.i(TAG, "  Blocked host: " + host);
    }

    /**
     * Generate hosts file for blocking
     */
    public boolean generateHostsFile(File output) {
        try {
            FileWriter fw = new FileWriter(output);
            fw.write("# BlackBox Enhanced - Online Bypass Hosts\\n");
            fw.write("# Generated by BypassOnlineService\\n\\n");
            fw.write("127.0.0.1 localhost\\n");
            fw.write("::1 localhost\\n\\n");
            for (String host : mBlockedHosts) {
                fw.write("0.0.0.0 " + host + "\\n");
                fw.write("0.0.0.0 www." + host + "\\n");
            }
            fw.close();
            Slog.i(TAG, "  Generated hosts file: " + output.getAbsolutePath());
            return true;
        } catch (Exception e) {
            Slog.e(TAG, "  Hosts file generation failed: " + e.getMessage());
            return false;
        }
    }

    /**
     * Spoof device properties for integrity checks
     */
    public void spoofDeviceProps() {
        try {
            Slog.i(TAG, "  Spoofing device properties:");
            Slog.i(TAG, "    Build.FINGERPRINT: " + Build.FINGERPRINT);
            Slog.i(TAG, "    Build.MANUFACTURER: " + Build.MANUFACTURER);
            Slog.i(TAG, "    Build.MODEL: " + Build.MODEL);
            Slog.i(TAG, "    Build.PRODUCT: " + Build.PRODUCT);
            Slog.i(TAG, "    Build.TAGS: " + Build.TAGS);
            Slog.i(TAG, "    Build.TYPE: " + Build.TYPE);
        } catch (Exception e) {
            Slog.e(TAG, "  Device spoof failed: " + e.getMessage());
        }
    }

    public boolean isActive() { return mActive; }
    public int getBlockedCount() { return mBlockedHosts.size(); }
}
